### ISSUE TITLE
remote start with CLI argument

### ISSUE THREAD

**Issue by mconlow** [G-Two/subarulink#14]
Small thing: when I run `subarulink -v 2 remote_start` I get the following error. It doesn't seem to accept remote_start on as it does in interactive mode

Traceback (most recent call last):
  File "/Users/local_user/Development/subaru/venv/bin/subarulink", line 10, in <module>
    sys.exit(main())
  File "/Users/local_user/Development/subaru/venv/lib/python3.7/site-packages/subarulink/app/cli.py", line 567, in main
    LOOP.run_until_complete(cli.single_command(args.command, args.vin))
  File "/Users/local_user/.pyenv/versions/3.7.3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/local_user/Development/subaru/venv/lib/python3.7/site-packages/subarulink/app/cli.py", line 459, in single_command
    self._config["hvac"]["rear_ac"],
TypeError: remote_start() takes 3 positional arguments but 10 were given
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10d03d160>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x10cffbc10>, 1.597272416)]']
connector: <aiohttp.connector.TCPConnector object at 0x10d03d208>

**Comment by G-Two** [comment]
Thanks, I'll fix it with the next update (hopefully tonight)
